CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS categories
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS events
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title                   VARCHAR(120) NOT NULL,
    annotation              VARCHAR(2000) NOT NULL,
    category_id             BIGINT,
    paid                    BOOLEAN NOT NULL,
    event_date              TIMESTAMP NOT NULL,
    initiator_id            BIGINT NOT NULL,
    lat                     DOUBLE PRECISION NOT NULL,
    lon                     DOUBLE PRECISION NOT NULL,
    description             VARCHAR(7000) NOT NULL,
    participant_limit       INTEGER NOT NULL,
    state                   VARCHAR(20) NOT NULL,
    created_on              TIMESTAMP NOT NULL,
    published_on            TIMESTAMP,
    requested_moderation    BOOLEAN NOT NULL,

    CONSTRAINT fk_event_category FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE CASCADE,
    CONSTRAINT fk_event_initiator FOREIGN KEY (initiator_id) REFERENCES users(id) ON DELETE CASCADE
);